data = {
    # Computer Science / Research
    "What is Python?": {"pclass": "Computer Science", "sclass": "Research/Informative", "Profane": "No", "Writing": "No", "Context": "No"},
    "How does a binary search algorithm work?": {"pclass": "Computer Science", "sclass": "Research/Informative", "Profane": "No", "Writing": "No", "Context": "No"},
    "What is the difference between Java and JavaScript?": {"pclass": "Computer Science", "sclass": "Research/Informative", "Profane": "No", "Writing": "No", "Context": "No"},
    "Explain object-oriented programming concepts.": {"pclass": "Computer Science", "sclass": "Research/Informative", "Profane": "No", "Writing": "No", "Context": "No"},
    "What are the key features of Linux?": {"pclass": "Computer Science", "sclass": "Research/Informative", "Profane": "No", "Writing": "No", "Context": "No"},
    "How does a neural network learn?": {"pclass": "Computer Science", "sclass": "Research/Informative", "Profane": "No", "Writing": "No", "Context": "No"},
    "What is the function of an operating system?": {"pclass": "Computer Science", "sclass": "Research/Informative", "Profane": "No", "Writing": "No", "Context": "No"},
    "How do databases store information?": {"pclass": "Computer Science", "sclass": "Research/Informative", "Profane": "No", "Writing": "No", "Context": "No"},
    "Explain recursion with an example.": {"pclass": "Computer Science", "sclass": "Research/Informative", "Profane": "No", "Writing": "No", "Context": "No"},
    "What is a hash table and how does it work?": {"pclass": "Computer Science", "sclass": "Research/Informative", "Profane": "No", "Writing": "No", "Context": "No"},
    "Describe the differences between TCP and UDP.": {"pclass": "Computer Science", "sclass": "Research/Informative", "Profane": "No", "Writing": "No", "Context": "No"},
    "What are some common programming paradigms?": {"pclass": "Computer Science", "sclass": "Research/Informative", "Profane": "No", "Writing": "No", "Context": "No"},
    "How do compilers convert code into machine language?": {"pclass": "Computer Science", "sclass": "Research/Informative", "Profane": "No", "Writing": "No", "Context": "No"},
    "What is the purpose of version control systems?": {"pclass": "Computer Science", "sclass": "Research/Informative", "Profane": "No", "Writing": "No", "Context": "No"},
    "Explain cloud computing in simple terms.": {"pclass": "Computer Science", "sclass": "Research/Informative", "Profane": "No", "Writing": "No", "Context": "No"},
    
    # History / Research
    "Who was Ghengis Khan?": {"pclass": "History", "sclass": "Research/Informative", "Profane": "No", "Writing": "No", "Context": "No"},
    "What caused the fall of the Roman Empire?": {"pclass": "History", "sclass": "Research/Informative", "Profane": "No", "Writing": "No", "Context": "No"},
    "Explain the significance of the French Revolution.": {"pclass": "History", "sclass": "Research/Informative", "Profane": "No", "Writing": "No", "Context": "No"},
    "Who was Cleopatra?": {"pclass": "History", "sclass": "Research/Informative", "Profane": "No", "Writing": "No", "Context": "No"},
    "What were the main causes of World War I?": {"pclass": "History", "sclass": "Research/Informative", "Profane": "No", "Writing": "No", "Context": "No"},
    "Describe the Renaissance period in Europe.": {"pclass": "History", "sclass": "Research/Informative", "Profane": "No", "Writing": "No", "Context": "No"},
    "What led to the American Civil War?": {"pclass": "History", "sclass": "Research/Informative", "Profane": "No", "Writing": "No", "Context": "No"},
    "Who was Napoleon Bonaparte?": {"pclass": "History", "sclass": "Research/Informative", "Profane": "No", "Writing": "No", "Context": "No"},
    "Explain the Cold War in simple terms.": {"pclass": "History", "sclass": "Research/Informative", "Profane": "No", "Writing": "No", "Context": "No"},
    "What was the Industrial Revolution?": {"pclass": "History", "sclass": "Research/Informative", "Profane": "No", "Writing": "No", "Context": "No"},
    "Who signed the Magna Carta?": {"pclass": "History", "sclass": "Research/Informative", "Profane": "No", "Writing": "No", "Context": "No"},
    "Describe the causes of the French and Indian War.": {"pclass": "History", "sclass": "Research/Informative", "Profane": "No", "Writing": "No", "Context": "No"},
    "What was the significance of the Berlin Wall?": {"pclass": "History", "sclass": "Research/Informative", "Profane": "No", "Writing": "No", "Context": "No"},
    "Who were the Vikings and where did they travel?": {"pclass": "History", "sclass": "Research/Informative", "Profane": "No", "Writing": "No", "Context": "No"},
    "What is the history of the Silk Road?": {"pclass": "History", "sclass": "Research/Informative", "Profane": "No", "Writing": "No", "Context": "No"},
    
    # Self Help / Advice
    "How can I study more effectively?": {"pclass": "Self Help", "sclass": "Advice/Guidance", "Profane": "No", "Writing": "No", "Context": "No"},
    "What time should I go to bed?": {"pclass": "Self Help", "sclass": "Advice/Guidance", "Profane": "No", "Writing": "No", "Context": "No"},
    "How do I improve my focus while working?": {"pclass": "Self Help", "sclass": "Advice/Guidance", "Profane": "No", "Writing": "No", "Context": "No"},
    "How can I manage my stress better?": {"pclass": "Self Help", "sclass": "Advice/Guidance", "Profane": "No", "Writing": "No", "Context": "No"},
    "What are good habits for productivity?": {"pclass": "Self Help", "sclass": "Advice/Guidance", "Profane": "No", "Writing": "No", "Context": "No"},
    "How can I improve my memory?": {"pclass": "Self Help", "sclass": "Advice/Guidance", "Profane": "No", "Writing": "No", "Context": "No"},
    "What are effective time management strategies?": {"pclass": "Self Help", "sclass": "Advice/Guidance", "Profane": "No", "Writing": "No", "Context": "No"},
    "How do I stay motivated to exercise?": {"pclass": "Self Help", "sclass": "Advice/Guidance", "Profane": "No", "Writing": "No", "Context": "No"},
    "What are tips for better concentration?": {"pclass": "Self Help", "sclass": "Advice/Guidance", "Profane": "No", "Writing": "No", "Context": "No"},
    "How can I build confidence?": {"pclass": "Self Help", "sclass": "Advice/Guidance", "Profane": "No", "Writing": "No", "Context": "No"},
    "How can I improve my public speaking skills?": {"pclass": "Self Help", "sclass": "Advice/Guidance", "Profane": "No", "Writing": "No", "Context": "No"},
    "What are ways to maintain a positive mindset?": {"pclass": "Self Help", "sclass": "Advice/Guidance", "Profane": "No", "Writing": "No", "Context": "No"},
    "How do I avoid procrastination?": {"pclass": "Self Help", "sclass": "Advice/Guidance", "Profane": "No", "Writing": "No", "Context": "No"},
    "What are effective study techniques for exams?": {"pclass": "Self Help", "sclass": "Advice/Guidance", "Profane": "No", "Writing": "No", "Context": "No"},
    "How can I better handle criticism?": {"pclass": "Self Help", "sclass": "Advice/Guidance", "Profane": "No", "Writing": "No", "Context": "No"},
    
    # Mathematics / Teaching
    "Whats the factored form of 2x^2 + 3x - 5": {"pclass": "Mathematics", "sclass": "Teaching/Instructing", "Profane": "No", "Writing": "No", "Context": "No"},
    "How can I solve for x in 7x + 8 = 5": {"pclass": "Mathematics", "sclass": "Teaching/Instructing", "Profane": "No", "Writing": "No", "Context": "No"},
    "What is the derivative of x^2 + 3x?": {"pclass": "Mathematics", "sclass": "Teaching/Instructing", "Profane": "No", "Writing": "No", "Context": "No"},
    "How do you calculate the area of a circle?": {"pclass": "Mathematics", "sclass": "Teaching/Instructing", "Profane": "No", "Writing": "No", "Context": "No"},
    "Explain the Pythagorean theorem with an example.": {"pclass": "Mathematics", "sclass": "Teaching/Instructing", "Profane": "No", "Writing": "No", "Context": "No"},
    "How do you solve a quadratic equation?": {"pclass": "Mathematics", "sclass": "Teaching/Instructing", "Profane": "No", "Writing": "No", "Context": "No"},
    "What is an integral and how is it calculated?": {"pclass": "Mathematics", "sclass": "Teaching/Instructing", "Profane": "No", "Writing": "No", "Context": "No"},
    "Explain how to find the slope of a line.": {"pclass": "Mathematics", "sclass": "Teaching/Instructing", "Profane": "No", "Writing": "No", "Context": "No"},
    "What is the difference between permutation and combination?": {"pclass": "Mathematics", "sclass": "Teaching/Instructing", "Profane": "No", "Writing": "No", "Context": "No"},
    "How do you calculate the volume of a cylinder?": {"pclass": "Mathematics", "sclass": "Teaching/Instructing", "Profane": "No", "Writing": "No", "Context": "No"},
    "Explain the concept of limits in calculus.": {"pclass": "Mathematics", "sclass": "Teaching/Instructing", "Profane": "No", "Writing": "No", "Context": "No"},
    "How do you convert fractions to decimals?": {"pclass": "Mathematics", "sclass": "Teaching/Instructing", "Profane": "No", "Writing": "No", "Context": "No"},
    "What are prime numbers and how to identify them?": {"pclass": "Mathematics", "sclass": "Teaching/Instructing", "Profane": "No", "Writing": "No", "Context": "No"},
    "Explain the difference between mean, median, and mode.": {"pclass": "Mathematics", "sclass": "Teaching/Instructing", "Profane": "No", "Writing": "No", "Context": "No"},
    "How do you solve systems of linear equations?": {"pclass": "Mathematics", "sclass": "Teaching/Instructing", "Profane": "No", "Writing": "No", "Context": "No"},

    # ----------------- Research/Informative -----------------
    # Writing: Yes, Context: Yes
    "Write a 1000-word report on the effects of global warming": {"pclass": "Environmental Science", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "Yes"},
    "Generate a research article summarizing black hole discoveries": {"pclass": "Physics", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "Yes"},
    "Create a literature review on machine learning algorithms": {"pclass": "Computer Science", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "Yes"},
    "Write a summary report on renewable energy trends": {"pclass": "Engineering", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "Yes"},
    "Generate an essay on the history of quantum physics": {"pclass": "Physics", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "Yes"},
    "Write a report on global biodiversity loss": {"pclass": "Biology", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "Yes"},
    "Create a research summary on AI ethics": {"pclass": "Computer Science", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "Yes"},
    "Write a report about the impact of deforestation": {"pclass": "Environmental Science", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "Yes"},
    "Generate an article on the latest COVID-19 research": {"pclass": "Medical Science", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "Yes"},
    "Write a research summary about space exploration missions": {"pclass": "Astronomy", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "Yes"},

    # Writing: Yes, Context: No
    "Write a 200-word essay on photosynthesis": {"pclass": "Biology", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Generate a short article on Newton's laws": {"pclass": "Physics", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Write a summary about the internet of things": {"pclass": "Computer Science", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Generate a short report on recycling": {"pclass": "Environmental Science", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Write a brief essay on the solar system": {"pclass": "Astronomy", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Write a summary about climate change causes": {"pclass": "Environmental Science", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Generate a brief article on renewable energy": {"pclass": "Engineering", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Write a short report on animal adaptation": {"pclass": "Biology", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Create a short essay on AI applications": {"pclass": "Computer Science", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Write a short summary of chemical bonding": {"pclass": "Chemistry", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},

    # Writing: No, Context: Yes
    "Explain quantum entanglement in simple terms": {"pclass": "Physics", "sclass": "Research/Informative", "Profane": "No", "Writing": "No", "Context": "Yes"},
    "Describe the effects of microplastics in oceans": {"pclass": "Environmental Science", "sclass": "Research/Informative", "Profane": "No", "Writing": "No", "Context": "Yes"},
    "Explain CRISPR gene editing and its applications": {"pclass": "Biology", "sclass": "Research/Informative", "Profane": "No", "Writing": "No", "Context": "Yes"},
    "Describe how blockchain works": {"pclass": "Computer Science", "sclass": "Research/Informative", "Profane": "No", "Writing": "No", "Context": "Yes"},
    "Explain black hole formation": {"pclass": "Astronomy", "sclass": "Research/Informative", "Profane": "No", "Writing": "No", "Context": "Yes"},
    "Describe the process of photosynthesis in detail": {"pclass": "Biology", "sclass": "Research/Informative", "Profane": "No", "Writing": "No", "Context": "Yes"},
    "Explain the difference between renewable and non-renewable energy": {"pclass": "Engineering", "sclass": "Research/Informative", "Profane": "No", "Writing": "No", "Context": "Yes"},
    "Describe the steps of evolution": {"pclass": "Biology", "sclass": "Research/Informative", "Profane": "No", "Writing": "No", "Context": "Yes"},
    "Explain how vaccines work": {"pclass": "Medical Science", "sclass": "Research/Informative", "Profane": "No", "Writing": "No", "Context": "Yes"},
    "Describe the effects of gravity on planetary orbits": {"pclass": "Physics", "sclass": "Research/Informative", "Profane": "No", "Writing": "No", "Context": "Yes"},

    # Writing: No, Context: No
    "What is Python?": {"pclass": "Computer Science", "sclass": "Research/Informative", "Profane": "No", "Writing": "No", "Context": "No"},
    "Why do leaves change color in autumn?": {"pclass": "Biology", "sclass": "Research/Informative", "Profane": "No", "Writing": "No", "Context": "No"},
    "Explain the theory of relativity": {"pclass": "Physics", "sclass": "Research/Informative", "Profane": "No", "Writing": "No", "Context": "No"},
    "What is machine learning?": {"pclass": "Computer Science", "sclass": "Research/Informative", "Profane": "No", "Writing": "No", "Context": "No"},
    "Why is the sky blue?": {"pclass": "Physics", "sclass": "Research/Informative", "Profane": "No", "Writing": "No", "Context": "No"},
    "What is photosynthesis?": {"pclass": "Biology", "sclass": "Research/Informative", "Profane": "No", "Writing": "No", "Context": "No"},
    "Explain Newton's first law": {"pclass": "Physics", "sclass": "Research/Informative", "Profane": "No", "Writing": "No", "Context": "No"},
    "What is the difference between RAM and ROM?": {"pclass": "Computer Science", "sclass": "Research/Informative", "Profane": "No", "Writing": "No", "Context": "No"},
    "Explain what a black hole is": {"pclass": "Astronomy", "sclass": "Research/Informative", "Profane": "No", "Writing": "No", "Context": "No"},
    "What is DNA?": {"pclass": "Biology", "sclass": "Research/Informative", "Profane": "No", "Writing": "No", "Context": "No"},

    # ----------------- Advice/Guidance -----------------
    # Writing: Yes, Context: Yes
    "Write a self-improvement plan for reducing procrastination": {"pclass": "Self Improvement", "sclass": "Advice/Guidance", "Profane": "No", "Writing": "Yes", "Context": "Yes"},
    "Generate a daily workout plan for beginners": {"pclass": "Health/Fitness", "sclass": "Advice/Guidance", "Profane": "No", "Writing": "Yes", "Context": "Yes"},
    "Write a guide on improving time management skills": {"pclass": "Self Improvement", "sclass": "Advice/Guidance", "Profane": "No", "Writing": "Yes", "Context": "Yes"},
    "Generate a report on stress management techniques": {"pclass": "Mental Health", "sclass": "Advice/Guidance", "Profane": "No", "Writing": "Yes", "Context": "Yes"},
    "Write a nutrition plan for a vegan diet": {"pclass": "Health", "sclass": "Advice/Guidance", "Profane": "No", "Writing": "Yes", "Context": "Yes"},
    "Create a financial budgeting plan for students": {"pclass": "Finance", "sclass": "Advice/Guidance", "Profane": "No", "Writing": "Yes", "Context": "Yes"},
    "Write a guide for improving public speaking skills": {"pclass": "Self Improvement", "sclass": "Advice/Guidance", "Profane": "No", "Writing": "Yes", "Context": "Yes"},
    "Generate a step-by-step plan to learn a new language": {"pclass": "Education", "sclass": "Advice/Guidance", "Profane": "No", "Writing": "Yes", "Context": "Yes"},
    "Write a productivity plan for remote workers": {"pclass": "Self Improvement", "sclass": "Advice/Guidance", "Profane": "No", "Writing": "Yes", "Context": "Yes"},
    "Create a plan to reduce screen time": {"pclass": "Self Improvement", "sclass": "Advice/Guidance", "Profane": "No", "Writing": "Yes", "Context": "Yes"},

    # Writing: Yes, Context: No
    "Write a short guide on improving concentration": {"pclass": "Self Improvement", "sclass": "Advice/Guidance", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Generate a brief guide on healthy eating": {"pclass": "Health", "sclass": "Advice/Guidance", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Write a guide on daily stretching exercises": {"pclass": "Health/Fitness", "sclass": "Advice/Guidance", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Create a guide on organizing your workspace": {"pclass": "Self Improvement", "sclass": "Advice/Guidance", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Write a short guide on improving sleep habits": {"pclass": "Health", "sclass": "Advice/Guidance", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Generate a brief guide on stress relief techniques": {"pclass": "Mental Health", "sclass": "Advice/Guidance", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Write a small guide on building self-confidence": {"pclass": "Self Improvement", "sclass": "Advice/Guidance", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Create a short guide on managing time effectively": {"pclass": "Self Improvement", "sclass": "Advice/Guidance", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Write a guide on improving study habits": {"pclass": "Education", "sclass": "Advice/Guidance", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Generate a brief guide on maintaining motivation": {"pclass": "Self Improvement", "sclass": "Advice/Guidance", "Profane": "No", "Writing": "Yes", "Context": "No"},

    # Writing: No, Context: Yes (Advice/Guidance)
    "How can I improve my memory effectively?": {"pclass": "Self Improvement", "sclass": "Advice/Guidance", "Profane": "No", "Writing": "No", "Context": "Yes"},
    "What strategies help reduce stress in the workplace?": {"pclass": "Mental Health", "sclass": "Advice/Guidance", "Profane": "No", "Writing": "No", "Context": "Yes"},
    "How do I stay motivated while learning a new skill?": {"pclass": "Self Improvement", "sclass": "Advice/Guidance", "Profane": "No", "Writing": "No", "Context": "Yes"},
    "What methods can improve sleep quality?": {"pclass": "Health", "sclass": "Advice/Guidance", "Profane": "No", "Writing": "No", "Context": "Yes"},
    "How can I reduce my screen time effectively?": {"pclass": "Self Improvement", "sclass": "Advice/Guidance", "Profane": "No", "Writing": "No", "Context": "Yes"},
    "What steps help develop better study habits?": {"pclass": "Education", "sclass": "Advice/Guidance", "Profane": "No", "Writing": "No", "Context": "Yes"},
    "How do I build self-confidence gradually?": {"pclass": "Self Improvement", "sclass": "Advice/Guidance", "Profane": "No", "Writing": "No", "Context": "Yes"},
    "What techniques help with time management?": {"pclass": "Self Improvement", "sclass": "Advice/Guidance", "Profane": "No", "Writing": "No", "Context": "Yes"},
    "How can I stay focused while working remotely?": {"pclass": "Self Improvement", "sclass": "Advice/Guidance", "Profane": "No", "Writing": "No", "Context": "Yes"},
    "What habits improve long-term productivity?": {"pclass": "Self Improvement", "sclass": "Advice/Guidance", "Profane": "No", "Writing": "No", "Context": "Yes"},

    # Writing: No, Context: No (Advice/Guidance)
    "How do I stay productive during the day?": {"pclass": "Self Improvement", "sclass": "Advice/Guidance", "Profane": "No", "Writing": "No", "Context": "No"},
    "What are tips for better focus while studying?": {"pclass": "Education", "sclass": "Advice/Guidance", "Profane": "No", "Writing": "No", "Context": "No"},
    "How can I manage stress daily?": {"pclass": "Mental Health", "sclass": "Advice/Guidance", "Profane": "No", "Writing": "No", "Context": "No"},
    "What are ways to stay motivated?": {"pclass": "Self Improvement", "sclass": "Advice/Guidance", "Profane": "No", "Writing": "No", "Context": "No"},
    "How do I improve my concentration?": {"pclass": "Self Improvement", "sclass": "Advice/Guidance", "Profane": "No", "Writing": "No", "Context": "No"},
    "What are effective time management tips?": {"pclass": "Self Improvement", "sclass": "Advice/Guidance", "Profane": "No", "Writing": "No", "Context": "No"},
    "How can I develop better study routines?": {"pclass": "Education", "sclass": "Advice/Guidance", "Profane": "No", "Writing": "No", "Context": "No"},
    "What is a good way to stay organized?": {"pclass": "Self Improvement", "sclass": "Advice/Guidance", "Profane": "No", "Writing": "No", "Context": "No"},
    "How do I avoid procrastination?": {"pclass": "Self Improvement", "sclass": "Advice/Guidance", "Profane": "No", "Writing": "No", "Context": "No"},
    "What are tips for healthy work-life balance?": {"pclass": "Self Improvement", "sclass": "Advice/Guidance", "Profane": "No", "Writing": "No", "Context": "No"},

    # ----------------- Teaching/Instructing -----------------
    # Writing: Yes, Context: Yes
    "Write a full lesson plan for teaching fractions to 5th graders": {"pclass": "Education/Mathematics", "sclass": "Teaching/Instructing", "Profane": "No", "Writing": "Yes", "Context": "Yes"},
    "Create a step-by-step guide to build a basic website using HTML/CSS": {"pclass": "Computer Science", "sclass": "Teaching/Instructing", "Profane": "No", "Writing": "Yes", "Context": "Yes"},
    "Write a tutorial on making sourdough bread from scratch": {"pclass": "Cooking", "sclass": "Teaching/Instructing", "Profane": "No", "Writing": "Yes", "Context": "Yes"},
    "Create a full exercise plan to train for a 5k race": {"pclass": "Health/Fitness", "sclass": "Teaching/Instructing", "Profane": "No", "Writing": "Yes", "Context": "Yes"},
    "Write a step-by-step coding assignment for Python beginners": {"pclass": "Computer Science", "sclass": "Teaching/Instructing", "Profane": "No", "Writing": "Yes", "Context": "Yes"},
    "Create a lesson plan to teach the water cycle": {"pclass": "Education/Science", "sclass": "Teaching/Instructing", "Profane": "No", "Writing": "Yes", "Context": "Yes"},
    "Write a tutorial on basic guitar chords for beginners": {"pclass": "Music", "sclass": "Teaching/Instructing", "Profane": "No", "Writing": "Yes", "Context": "Yes"},
    "Create a guide to build a birdhouse step by step": {"pclass": "DIY", "sclass": "Teaching/Instructing", "Profane": "No", "Writing": "Yes", "Context": "Yes"},
    "Write a lesson plan for teaching simple physics experiments": {"pclass": "Education/Physics", "sclass": "Teaching/Instructing", "Profane": "No", "Writing": "Yes", "Context": "Yes"},
    "Create a tutorial on drawing realistic faces": {"pclass": "Art", "sclass": "Teaching/Instructing", "Profane": "No", "Writing": "Yes", "Context": "Yes"},

    # Writing: Yes, Context: No
    "Write instructions for making a paper airplane": {"pclass": "DIY", "sclass": "Teaching/Instructing", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Write a guide to install Python on Windows": {"pclass": "Computer Science", "sclass": "Teaching/Instructing", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Write a tutorial for baking banana bread": {"pclass": "Cooking", "sclass": "Teaching/Instructing", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Write a coding exercise to reverse a string": {"pclass": "Computer Science", "sclass": "Teaching/Instructing", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Write instructions for drawing a cartoon cat": {"pclass": "Art", "sclass": "Teaching/Instructing", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Write a step-by-step guide to make scrambled eggs": {"pclass": "Cooking", "sclass": "Teaching/Instructing", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Write a short lesson on basic fractions": {"pclass": "Education/Mathematics", "sclass": "Teaching/Instructing", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Write a tutorial for tying a bow tie": {"pclass": "Fashion/Practical Skills", "sclass": "Teaching/Instructing", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Write instructions for setting up a tent": {"pclass": "Outdoor Skills", "sclass": "Teaching/Instructing", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Write a guide for planting indoor herbs": {"pclass": "Gardening", "sclass": "Teaching/Instructing", "Profane": "No", "Writing": "Yes", "Context": "No"},

    # Writing: No, Context: Yes
    "How do I perform CPR correctly?": {"pclass": "Health/First Aid", "sclass": "Teaching/Instructing", "Profane": "No", "Writing": "No", "Context": "Yes"},
    "How can I build a simple bird feeder?": {"pclass": "DIY", "sclass": "Teaching/Instructing", "Profane": "No", "Writing": "No", "Context": "Yes"},
    "How do I draw a realistic tree?": {"pclass": "Art", "sclass": "Teaching/Instructing", "Profane": "No", "Writing": "No", "Context": "Yes"},
    "How do I solve linear equations step by step?": {"pclass": "Mathematics", "sclass": "Teaching/Instructing", "Profane": "No", "Writing": "No", "Context": "Yes"},
    "How can I play a C major chord on guitar?": {"pclass": "Music", "sclass": "Teaching/Instructing", "Profane": "No", "Writing": "No", "Context": "Yes"},
    "How do I set up a basic HTML page?": {"pclass": "Computer Science", "sclass": "Teaching/Instructing", "Profane": "No", "Writing": "No", "Context": "Yes"},
    "How do I make a simple paper flower?": {"pclass": "Art/DIY", "sclass": "Teaching/Instructing", "Profane": "No", "Writing": "No", "Context": "Yes"},
    "How can I tie my shoelaces faster?": {"pclass": "Practical Skills", "sclass": "Teaching/Instructing", "Profane": "No", "Writing": "No", "Context": "Yes"},
    "How do I bake a basic cake?": {"pclass": "Cooking", "sclass": "Teaching/Instructing", "Profane": "No", "Writing": "No", "Context": "Yes"},
    "How do I draw a simple cartoon character?": {"pclass": "Art", "sclass": "Teaching/Instructing", "Profane": "No", "Writing": "No", "Context": "Yes"},

    # Writing: No, Context: No
    "Teach me how to tie a tie": {"pclass": "Fashion/Practical Skills", "sclass": "Teaching/Instructing", "Profane": "No", "Writing": "No", "Context": "No"},
    "Teach me to draw a realistic eye": {"pclass": "Art", "sclass": "Teaching/Instructing", "Profane": "No", "Writing": "No", "Context": "No"},
    "Show me how to solve a quadratic equation": {"pclass": "Mathematics", "sclass": "Teaching/Instructing", "Profane": "No", "Writing": "No", "Context": "No"},
    "Teach me how to play a C chord on piano": {"pclass": "Music", "sclass": "Teaching/Instructing", "Profane": "No", "Writing": "No", "Context": "No"},
    "Show me how to bake cookies": {"pclass": "Cooking", "sclass": "Teaching/Instructing", "Profane": "No", "Writing": "No", "Context": "No"},
    "Teach me the steps of photosynthesis": {"pclass": "Biology/Education", "sclass": "Teaching/Instructing", "Profane": "No", "Writing": "No", "Context": "No"},
    "Teach me how to do CPR": {"pclass": "Health/First Aid", "sclass": "Teaching/Instructing", "Profane": "No", "Writing": "No", "Context": "No"},
    "Show me how to draw a simple house": {"pclass": "Art", "sclass": "Teaching/Instructing", "Profane": "No", "Writing": "No", "Context": "No"},
    "Teach me to solve a system of equations": {"pclass": "Mathematics", "sclass": "Teaching/Instructing", "Profane": "No", "Writing": "No", "Context": "No"},
    "Show me how to set up a basic website": {"pclass": "Computer Science", "sclass": "Teaching/Instructing", "Profane": "No", "Writing": "No", "Context": "No"}
}
