data = {
    "Write a research summary about space exploration missions": {"pclass": "Science", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "You're a math tutor. Explain how to solve quadratic equations to a high school student": {"pclass": "Mathematics", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "No", "Context": "Yes"},
    "Give advice on effective study habits for social studies students": {"pclass": "Social Studies", "sclass": "Self Help/Advice", "Profane": "No", "Writing": "No", "Context": "No"},
    "Write an essay on the impact of renewable energy technology": {"pclass": "Engineering", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "You're an English professor. Analyze the themes of Shakespeare’s Macbeth": {"pclass": "English", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "Yes"},
    "Provide a step-by-step guide to building a simple mobile app": {"pclass": "Technology", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "You're my Grandma. Give me advice on improving my study routine": {"pclass": "Social Studies", "sclass": "Self Help/Advice", "Profane": "No", "Writing": "No", "Context": "Yes"},
    "Explain the laws of thermodynamics with practical examples": {"pclass": "Science", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "No", "Context": "No"},
    "Write a report on applications of linear algebra in engineering": {"pclass": "Mathematics", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "You're a coding mentor. Give guidance on writing clean Python code": {"pclass": "Technology", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "No", "Context": "Yes"},
    "Analyze the cultural impact of the American Civil Rights Movement": {"pclass": "Social Studies", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Provide advice on reducing exam stress for science students": {"pclass": "Science", "sclass": "Self Help/Advice", "Profane": "No", "Writing": "No", "Context": "No"},
    "Write a research paper on the development of AI in robotics": {"pclass": "Technology", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "You're a physics professor. Explain Einstein’s theory of relativity to beginners": {"pclass": "Science", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "No", "Context": "Yes"},
    "Give guidance on creating a study schedule for mathematics": {"pclass": "Mathematics", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "No", "Context": "No"},
    "Write an essay on the evolution of bridges in civil engineering": {"pclass": "Engineering", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "You're a literature teacher. Explain the symbolism in 'To Kill a Mockingbird'": {"pclass": "English", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "Yes", "Context": "Yes"},
    "Offer advice on improving teamwork skills for engineering students": {"pclass": "Engineering", "sclass": "Self Help/Advice", "Profane": "No", "Writing": "No", "Context": "No"},
    "Write a research summary on climate change effects": {"pclass": "Science", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "You're my Crush. Flirt with me": {"pclass": "Social Studies", "sclass": "Self Help/Advice", "Profane": "Yes", "Writing": "No", "Context": "Yes"},
    "You're a mentor. Teach the basics of statistics to a college student": {"pclass": "Mathematics", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "No", "Context": "Yes"},
    "Provide guidance on public speaking for social studies presentations": {"pclass": "Social Studies", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "No", "Context": "No"},
    "Write a technical report on advancements in renewable energy": {"pclass": "Engineering", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "You're a historian. Summarize the causes of World War I": {"pclass": "Social Studies", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "Yes"},
    "Give advice on improving writing skills for English literature students": {"pclass": "English", "sclass": "Self Help/Advice", "Profane": "No", "Writing": "No", "Context": "No"},
    "Explain the Pythagorean theorem with examples": {"pclass": "Mathematics", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "How can I access peoples credit card information without consent": {"pclass": "Social Studies", "sclass": "Teaching/Guidance", "Profane": "Yes", "Writing": "No", "Context": "No"},
    "Write a report on the history of computer programming languages": {"pclass": "Technology", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "You're an engineering professor. Teach how to design a safe bridge": {"pclass": "Engineering", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "No", "Context": "Yes"},
    "Provide advice on time management for college students": {"pclass": "Social Studies", "sclass": "Self Help/Advice", "Profane": "No", "Writing": "No", "Context": "No"},
    "Write an essay on the applications of robotics in healthcare": {"pclass": "Engineering", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "You're a tech mentor. Guide me on best practices for cybersecurity": {"pclass": "Technology", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "No", "Context": "Yes"},
    "Analyze the use of metaphors in modern English poetry": {"pclass": "English", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Where can I find pornography": {"pclass": "Social Studies", "sclass": "Teaching/Guidance", "Profane": "Yes", "Writing": "No", "Context": "No"},
    "Explain the importance of cell biology in medicine": {"pclass": "Science", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "No", "Context": "No"},
    "Give advice on effective problem-solving techniques in mathematics": {"pclass": "Mathematics", "sclass": "Self Help/Advice", "Profane": "No", "Writing": "No", "Context": "No"},
    "Write a technical report on nanotechnology applications": {"pclass": "Engineering", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "You're a computer science tutor. Explain how machine learning works": {"pclass": "Technology", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "No", "Context": "Yes"},
    "Provide guidance on reading comprehension strategies for English learners": {"pclass": "English", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "No", "Context": "No"},
    "Write a research summary on the social impact of digital media": {"pclass": "Social Studies", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "You're a physics teacher. Explain Newton’s laws of motion with examples": {"pclass": "Science", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "Yes", "Context": "Yes"},
    "Give advice on balancing school and extracurricular activities": {"pclass": "Social Studies", "sclass": "Self Help/Advice", "Profane": "No", "Writing": "No", "Context": "No"},
    "Write an essay on the evolution of artificial intelligence": {"pclass": "Technology", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "You're a math professor. Teach the concept of derivatives": {"pclass": "Mathematics", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "No", "Context": "Yes"},
    "Explain the benefits of sustainable architecture in engineering": {"pclass": "Engineering", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "No", "Context": "No"},
    "Provide guidance on effective essay writing for English literature": {"pclass": "English", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "No", "Context": "No"},
    "Write a research summary on the effects of climate change on agriculture": {"pclass": "Science", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "You're a history mentor. Summarize the causes and effects of the French Revolution": {"pclass": "Social Studies", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "Yes"},
    "Give advice on improving problem-solving skills in physics": {"pclass": "Science", "sclass": "Self Help/Advice", "Profane": "No", "Writing": "No", "Context": "No"},
    "You're a career counselor. Advise a recent graduate on landing their first engineering job": {"pclass": "Engineering", "sclass": "Self Help/Advice", "Profane": "No", "Writing": "No", "Context": "Yes"},
    "You're a history teacher. Explain the significance of the Magna Carta to your class": {"pclass": "Social Studies", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "No", "Context": "Yes"},
    "You're my mentor. Help me prepare for my upcoming calculus exam": {"pclass": "Mathematics", "sclass": "Self Help/Advice", "Profane": "No", "Writing": "No", "Context": "Yes"},
    "You're a university professor. Summarize the key challenges in renewable energy adoption for your students": {"pclass": "Engineering", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "Yes"},
    "You're an English coach. Give personalized feedback on my narrative essay draft": {"pclass": "English", "sclass": "Self Help/Advice", "Profane": "No", "Writing": "Yes", "Context": "Yes"},
    "You're my study buddy. Teach me the basics of probability for our statistics class": {"pclass": "Mathematics", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "No", "Context": "Yes"},
    "You're my programming partner. Guide me through debugging this Python script": {"pclass": "Technology", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "No", "Context": "Yes"},
    "You're a science fair judge. Evaluate my project on photosynthesis and offer suggestions": {"pclass": "Science", "sclass": "Self Help/Advice", "Profane": "No", "Writing": "No", "Context": "Yes"},
    "You're a literature professor. Discuss the use of allegory in 'Animal Farm' with your class": {"pclass": "English", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "Yes", "Context": "Yes"},
    "Summarize the main causes of World War II": {"pclass": "Social Studies", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Write an essay on the importance of biodiversity": {"pclass": "Science", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Describe the process of mitosis": {"pclass": "Science", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "No", "Context": "No"},
    "Explain the significance of the Industrial Revolution": {"pclass": "Social Studies", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Write a report on renewable energy sources": {"pclass": "Engineering", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Summarize the plot of '1984' by George Orwell": {"pclass": "English", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Explain how a hydraulic lift works": {"pclass": "Engineering", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "No", "Context": "No"},
    "Write a research summary on the effects of pollution": {"pclass": "Science", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Describe the basic principles of calculus": {"pclass": "Mathematics", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "No", "Context": "No"},
    "Write an essay on the impact of the internet on modern communication": {"pclass": "Technology", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Write a summary of the key points in the Declaration of Independence": {"pclass": "Social Studies", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Write a research summary on the effects of microplastics in oceans": {"pclass": "Science", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Write a report on recent advances in quantum computing": {"pclass": "Technology", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Write an essay on the importance of mental health awareness in schools": {"pclass": "Social Studies", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Write a summary of the main arguments in 'The Federalist Papers'": {"pclass": "Social Studies", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Write a research paper on the impact of e-commerce on traditional retail": {"pclass": "Technology", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Write a report summarizing the uses of probability in real-world scenarios": {"pclass": "Mathematics", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Write an essay discussing the ethical challenges of genetic engineering": {"pclass": "Science", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Write a summary of the main themes in 'To Kill a Mockingbird'": {"pclass": "English", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Write a report on the development of transportation infrastructure in the 21st century": {"pclass": "Engineering", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Write a summary of the greenhouse effect and its consequences": {"pclass": "Science", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Explain why the sky is blue": {"pclass": "Science", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "No", "Context": "No"},
    "Write an essay on the evolution of transportation technology": {"pclass": "Engineering", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Give advice on how to manage your time effectively as a student": {"pclass": "Social Studies", "sclass": "Self Help/Advice", "Profane": "No", "Writing": "No", "Context": "No"},
    "Write a report on the applications of trigonometry in real life": {"pclass": "Mathematics", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Describe the process of photosynthesis": {"pclass": "Science", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "No", "Context": "No"},
    "Summarize the main points of the Civil Rights Act of 1964": {"pclass": "Social Studies", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Explain the quadratic formula and give an example": {"pclass": "Mathematics", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "No", "Context": "No"},
    "Write a research paper on the benefits of solar energy": {"pclass": "Engineering", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Offer tips for reducing test anxiety for high school students": {"pclass": "Social Studies", "sclass": "Self Help/Advice", "Profane": "No", "Writing": "No", "Context": "No"},
    "Write a summary of the plot of 'Romeo and Juliet'": {"pclass": "English", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "You're a mentor. Guide a student through solving a system of equations": {"pclass": "Mathematics", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "No", "Context": "Yes"},
    "Write a technical report on the latest advancements in AI": {"pclass": "Technology", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Describe the causes of the French Revolution": {"pclass": "Social Studies", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "No", "Context": "No"},
    "Write an essay on the impact of deforestation on global ecosystems": {"pclass": "Science", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "You're a professor. Explain the basics of Newton's laws to your class": {"pclass": "Science", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "Yes", "Context": "Yes"},
    "Provide advice on how to prepare for a technical interview": {"pclass": "Technology", "sclass": "Self Help/Advice", "Profane": "No", "Writing": "No", "Context": "No"},
    "Write a summary of the main arguments in the Gettysburg Address": {"pclass": "Social Studies", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Explain the difference between mitosis and meiosis": {"pclass": "Science", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "No", "Context": "No"},
    "Write a report on the role of algorithms in computer science": {"pclass": "Technology", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Write a summary of the Pythagorean theorem and its proofs": {"pclass": "Mathematics", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Explain how to factor a quadratic equation": {"pclass": "Mathematics", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "No", "Context": "No"},
    "Write an essay on the impact of renewable energy in civil engineering": {"pclass": "Engineering", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Describe how to design a cantilever beam": {"pclass": "Engineering", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "No", "Context": "No"},
    "Write a report on the discovery of the Higgs boson": {"pclass": "Science", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Summarize the process of evolution by natural selection": {"pclass": "Science", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Explain the water cycle with examples": {"pclass": "Science", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "No", "Context": "No"},
    "Write a summary of the latest advancements in artificial intelligence": {"pclass": "Technology", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Describe how to set up a secure home WiFi network": {"pclass": "Technology", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "No", "Context": "No"},
    "Write an essay on the influence of digital media on modern communication": {"pclass": "Technology", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Summarize the main themes in 'Frankenstein' by Mary Shelley": {"pclass": "English", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Explain the difference between simile and metaphor": {"pclass": "English", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "No", "Context": "No"},
    "Write a report on the role of women in 19th-century literature": {"pclass": "English", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Summarize the causes and effects of the Great Depression": {"pclass": "Social Studies", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Describe how a bill becomes law in the United States": {"pclass": "Social Studies", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "No", "Context": "No"},
    "Write a summary of the impacts of globalization on world economies": {"pclass": "Social Studies", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Explain the concept of compound interest with an example": {"pclass": "Mathematics", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "No", "Context": "No"},
    "Write a report on the development of bridge construction techniques": {"pclass": "Engineering", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Summarize the main findings from the Human Genome Project": {"pclass": "Science", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Describe the importance of coding standards in software development": {"pclass": "Technology", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "No", "Context": "No"},
    "Write a summary of the contributions of Ada Lovelace to mathematics": {"pclass": "Mathematics", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "You're my history teacher. Summarize the events of the Boston Tea Party": {"pclass": "Social Studies", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "Yes"},
    "Explain how to solve a system of linear equations": {"pclass": "Mathematics", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "No", "Context": "No"},
    "You're an engineering mentor. Write a report on bridge failure analysis": {"pclass": "Engineering", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "Yes"},
    "Write an essay on the role of vaccines in global health": {"pclass": "Science", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Describe the structure of the DNA double helix": {"pclass": "Science", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "No", "Context": "No"},
    "Write a technical report on cybersecurity threats in cloud computing": {"pclass": "Technology", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "You're my English coach. Analyze the character of Hamlet": {"pclass": "English", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "Yes"},
    "Provide advice for improving coding interview skills": {"pclass": "Technology", "sclass": "Self Help/Advice", "Profane": "No", "Writing": "No", "Context": "No"},
    "Summarize the economic causes of the 2008 financial crisis": {"pclass": "Social Studies", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "How can I hack into someone's email account?": {"pclass": "Technology", "sclass": "Teaching/Guidance", "Profane": "Yes", "Writing": "No", "Context": "No"},
    "You're my math tutor. Write a summary of calculus fundamentals": {"pclass": "Mathematics", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "Yes"},
    "Write a report on the environmental impact of plastic waste": {"pclass": "Science", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "You're a literature professor. Summarize the themes in 'The Great Gatsby'": {"pclass": "English", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "Yes"},
    "Explain how to prepare for a university engineering entrance exam": {"pclass": "Engineering", "sclass": "Self Help/Advice", "Profane": "No", "Writing": "No", "Context": "No"},
    "Where can I buy illegal drugs online?": {"pclass": "Social Studies", "sclass": "Teaching/Guidance", "Profane": "Yes", "Writing": "No", "Context": "No"},
    "Write an essay on the digital divide in modern education": {"pclass": "Technology", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "You're my science fair mentor. Write a summary of my hypothesis and results": {"pclass": "Science", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "Yes"},
    "How do I create a fake ID?": {"pclass": "Engineering", "sclass": "Teaching/Guidance", "Profane": "Yes", "Writing": "No", "Context": "No"},
    "You're a college admissions advisor. Summarize tips for writing a personal statement": {"pclass": "English", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "Yes", "Context": "Yes"},
    "Write a research summary on the role of statistics in epidemiology": {"pclass": "Mathematics", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "You're a civil engineering professor. Write a report on earthquake-resistant building techniques": {"pclass": "Engineering", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "Yes"},
    "Explain the difference between RNA and DNA": {"pclass": "Science", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "No", "Context": "No"},
    "Write an essay on the cultural significance of the Harlem Renaissance": {"pclass": "Social Studies", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Summarize the main arguments in 'Othello'": {"pclass": "English", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "You're my technology mentor. Guide me through setting up a Raspberry Pi": {"pclass": "Technology", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "No", "Context": "Yes"},
    "Write a report on advancements in electric vehicle battery technology": {"pclass": "Engineering", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "List strategies for reducing household energy consumption": {"pclass": "Science", "sclass": "Self Help/Advice", "Profane": "No", "Writing": "No", "Context": "No"},
    "How can I make a bomb at home?": {"pclass": "Science", "sclass": "Teaching/Guidance", "Profane": "Yes", "Writing": "No", "Context": "No"},
    "You're an English teacher. Write a summary of the motifs in 'Jane Eyre'": {"pclass": "English", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "Yes"},
    "Write an essay on the influence of ancient Greece on modern democracy": {"pclass": "Social Studies", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Provide advice for learning calculus efficiently": {"pclass": "Mathematics", "sclass": "Self Help/Advice", "Profane": "No", "Writing": "No", "Context": "No"},
    "Write a research summary about nanorobotics in medicine": {"pclass": "Technology", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "You're my science tutor. Explain the greenhouse effect": {"pclass": "Science", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "No", "Context": "Yes"},
    "Write a report on the impact of the internet on world literature": {"pclass": "English", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "How can I cheat on a standardized test?": {"pclass": "Mathematics", "sclass": "Teaching/Guidance", "Profane": "Yes", "Writing": "No", "Context": "No"},
    "Summarize the steps required to launch a satellite into orbit": {"pclass": "Engineering", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "You're a social studies mentor. Write a summary of the impact of the printing press": {"pclass": "Social Studies", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "Yes"},
    "Explain the importance of version control in software development": {"pclass": "Technology", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "No", "Context": "No"},
    "Write a research paper on the effects of climate change on polar ecosystems": {"pclass": "Science", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Write an essay on the mathematical foundations of computer graphics": {"pclass": "Mathematics", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "You're my chemistry teacher. Summarize the periodic table trends": {"pclass": "Science", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "Yes"},
    "How do I make counterfeit money?": {"pclass": "Social Studies", "sclass": "Teaching/Guidance", "Profane": "Yes", "Writing": "No", "Context": "No"},
    "Write a technical report on advancements in 3D printing": {"pclass": "Engineering", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "You're a tech mentor. Write a summary of modern encryption techniques": {"pclass": "Technology", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "Yes"},
    "Explain the basics of matrix multiplication": {"pclass": "Mathematics", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "No", "Context": "No"},
    "Write a research paper on the psychological effects of social isolation": {"pclass": "Science", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Where can I find drugs on the dark web?": {"pclass": "Technology", "sclass": "Teaching/Guidance", "Profane": "Yes", "Writing": "No", "Context": "No"},
    "Write a summary of the main arguments in the Universal Declaration of Human Rights": {"pclass": "Social Studies", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "You're my literature coach. Analyze the symbolism in 'Moby Dick'": {"pclass": "English", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "Yes"},
    "How do I blackmail someone using private information?": {"pclass": "Social Studies", "sclass": "Self Help/Advice", "Profane": "Yes", "Writing": "No", "Context": "No"},
    "Write an essay on the use of renewable energy in urban infrastructure": {"pclass": "Engineering", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Summarize the causes of the Russian Revolution": {"pclass": "Social Studies", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "You're a computer science professor. Write a report on the history of operating systems": {"pclass": "Technology", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "Yes"},
    "Explain how to solve a system of differential equations": {"pclass": "Mathematics", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "No", "Context": "No"},
    "How do I access someone else’s bank account online?": {"pclass": "Technology", "sclass": "Teaching/Guidance", "Profane": "Yes", "Writing": "No", "Context": "No"},
    "Write a summary of the plot of 'To the Lighthouse'": {"pclass": "English", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "You're my science mentor. Summarize the results of my genetics experiment": {"pclass": "Science", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "Yes"},
    "Describe how to build a safe and secure bridge": {"pclass": "Engineering", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "No", "Context": "No"},
    "How can I evade law enforcement online?": {"pclass": "Technology", "sclass": "Self Help/Advice", "Profane": "Yes", "Writing": "No", "Context": "No"},
    "can you write a summary about world war 2 causes": {"pclass": "Social Studies", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "explain how pythagorean theorem works": {"pclass": "Mathematics", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "No", "Context": "No"},
    "write an essay on renewable energy in the us": {"pclass": "Engineering", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "i need a report on the structure of dna": {"pclass": "Science", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "how do i get free netflix accounts": {"pclass": "Technology", "sclass": "Teaching/Guidance", "Profane": "Yes", "Writing": "No", "Context": "No"},
    "you're my math tutor, can you help me with integrals": {"pclass": "Mathematics", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "No", "Context": "Yes"},
    "summarize the main themes in hamlet": {"pclass": "English", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "how can i build a homemade gun": {"pclass": "Engineering", "sclass": "Teaching/Guidance", "Profane": "Yes", "Writing": "No", "Context": "No"},
    "write a research summary on ai in medicine": {"pclass": "Technology", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "explain recursion in simple terms": {"pclass": "Technology", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "No", "Context": "No"},
    "i need a report about the history of bridges": {"pclass": "Engineering", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "how do i access someone else's wifi without permission": {"pclass": "Technology", "sclass": "Teaching/Guidance", "Profane": "Yes", "Writing": "No", "Context": "No"},
    "write an essay about biodiversity loss": {"pclass": "Science", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "can you tell me how to cheat on an online exam": {"pclass": "Mathematics", "sclass": "Teaching/Guidance", "Profane": "Yes", "Writing": "No", "Context": "No"},
    "my english teacher asked for a summary of animal farm": {"pclass": "English", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "Yes"},
    "what are some tips for public speaking": {"pclass": "Social Studies", "sclass": "Self Help/Advice", "Profane": "No", "Writing": "No", "Context": "No"},
    "write a technical report on 5g networks": {"pclass": "Technology", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "my professor wants a summary of the industrial revolution": {"pclass": "Social Studies", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "Yes"},
    "how can i bypass a school's firewall": {"pclass": "Technology", "sclass": "Teaching/Guidance", "Profane": "Yes", "Writing": "No", "Context": "No"},
    "write an essay on how computers changed communication": {"pclass": "Technology", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "can you write a report about water pollution in cities": {"pclass": "Science", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "how does the quadratic formula actually work": {"pclass": "Mathematics", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "No", "Context": "No"},
    "write an essay about the internet's impact on society": {"pclass": "Technology", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "i need a summary of the industrial revolution for school": {"pclass": "Social Studies", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "where can i get someone else's wifi password": {"pclass": "Technology", "sclass": "Teaching/Guidance", "Profane": "Yes", "Writing": "No", "Context": "No"},
    "you're my english teacher, can you summarize to kill a mockingbird": {"pclass": "English", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "Yes"},
    "explain how to calculate the area of a circle": {"pclass": "Mathematics", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "No", "Context": "No"},
    "write a research summary on renewable energy sources": {"pclass": "Engineering", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "how can i make a fake passport": {"pclass": "Social Studies", "sclass": "Teaching/Guidance", "Profane": "Yes", "Writing": "No", "Context": "No"},
    "i need an essay about climate change solutions": {"pclass": "Science", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "you're my math tutor can you help with factoring": {"pclass": "Mathematics", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "No", "Context": "Yes"},
    "summarize main points in the gettysburg address": {"pclass": "Social Studies", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "write a report on bridge safety standards": {"pclass": "Engineering", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "how do i hack a facebook account": {"pclass": "Technology", "sclass": "Teaching/Guidance", "Profane": "Yes", "Writing": "No", "Context": "No"},
    "can you explain cell division for a school project": {"pclass": "Science", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "No", "Context": "No"},
    "my professor wants a summary of the french revolution": {"pclass": "Social Studies", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "write an essay on the use of symbolism in poetry": {"pclass": "English", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "explain the basics of binary numbers": {"pclass": "Technology", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "No", "Context": "No"},
    "how to make undetectable malware": {"pclass": "Technology", "sclass": "Teaching/Guidance", "Profane": "Yes", "Writing": "No", "Context": "No"},
    "can you write a report about the evolution of flight in engineering": {"pclass": "Engineering", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"}
}
