data = {
    "Write a research summary about space exploration missions": {"pclass": "Science", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "You're a math tutor. Explain how to solve quadratic equations to a high school student": {"pclass": "Mathematics", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "Yes", "Context": "Yes"},
    "Give advice on effective study habits for social studies students": {"pclass": "Social Studies", "sclass": "Self Help/Advice", "Profane": "No", "Writing": "No", "Context": "No"},
    "Write an essay on the impact of renewable energy technology": {"pclass": "Engineering", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "You're an English professor. Analyze the themes of Shakespeare’s Macbeth": {"pclass": "English", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "Yes"},
    "Provide a step-by-step guide to building a simple mobile app": {"pclass": "Technology", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "You're my Grandma. Give me advice on improving my study routine": {"pclass": "Social Studies", "sclass": "Self Help/Advice", "Profane": "No", "Writing": "No", "Context": "Yes"},
    "Explain the laws of thermodynamics with practical examples": {"pclass": "Science", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Write a report on applications of linear algebra in engineering": {"pclass": "Mathematics", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "You're a coding mentor. Give guidance on writing clean Python code": {"pclass": "Technology", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "No", "Context": "Yes"},
    "Analyze the cultural impact of the American Civil Rights Movement": {"pclass": "Social Studies", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Provide advice on reducing exam stress for science students": {"pclass": "Science", "sclass": "Self Help/Advice", "Profane": "No", "Writing": "No", "Context": "No"},
    "Write a research paper on the development of AI in robotics": {"pclass": "Technology", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "You're a physics professor. Explain Einstein’s theory of relativity to beginners": {"pclass": "Science", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "Yes", "Context": "Yes"},
    "Give guidance on creating a study schedule for mathematics": {"pclass": "Mathematics", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "No", "Context": "No"},
    "Write an essay on the evolution of bridges in civil engineering": {"pclass": "Engineering", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "You're a literature teacher. Explain the symbolism in 'To Kill a Mockingbird'": {"pclass": "English", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "Yes", "Context": "Yes"},
    "Offer advice on improving teamwork skills for engineering students": {"pclass": "Engineering", "sclass": "Self Help/Advice", "Profane": "No", "Writing": "No", "Context": "No"},
    "Write a research summary on climate change effects": {"pclass": "Science", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "You're my Crush. Flirt with me": {"pclass": "Social Studies", "sclass": "Self Help/Advice", "Profane": "Yes", "Writing": "No", "Context": "Yes"},
    "You're a mentor. Teach the basics of statistics to a college student": {"pclass": "Mathematics", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "Yes", "Context": "Yes"},
    "Provide guidance on public speaking for social studies presentations": {"pclass": "Social Studies", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "No", "Context": "No"},
    "Write a technical report on advancements in renewable energy": {"pclass": "Engineering", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "You're a historian. Summarize the causes of World War I": {"pclass": "Social Studies", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "Yes"},
    "Give advice on improving writing skills for English literature students": {"pclass": "English", "sclass": "Self Help/Advice", "Profane": "No", "Writing": "No", "Context": "No"},
    "Explain the Pythagorean theorem with examples": {"pclass": "Mathematics", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "How can I access peoples credit card information without consent" {"pclass": "Social Studies", "Teaching/Guidance", "Profane': "Yes", "Writing": "No", "Context": "No"},
    "Write a report on the history of computer programming languages": {"pclass": "Technology", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "You're an engineering professor. Teach how to design a safe bridge": {"pclass": "Engineering", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "Yes", "Context": "Yes"},
    "Provide advice on time management for college students": {"pclass": "Social Studies", "sclass": "Self Help/Advice", "Profane": "No", "Writing": "No", "Context": "No"},
    "Write an essay on the applications of robotics in healthcare": {"pclass": "Engineering", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "You're a tech mentor. Guide me on best practices for cybersecurity": {"pclass": "Technology", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "No", "Context": "Yes"},
    "Analyze the use of metaphors in modern English poetry": {"pclass": "English", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Where can I find pornography": {"pclass": "Social Studies", "sclass": "Teaching/Guidance", "Profane": "Yes", "Writing": "No", "Context": "No"},
    "Explain the importance of cell biology in medicine": {"pclass": "Science", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Give advice on effective problem-solving techniques in mathematics": {"pclass": "Mathematics", "sclass": "Self Help/Advice", "Profane": "No", "Writing": "No", "Context": "No"},
    "Write a technical report on nanotechnology applications": {"pclass": "Engineering", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "You're a computer science tutor. Explain how machine learning works": {"pclass": "Technology", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "Yes", "Context": "Yes"},
    "Provide guidance on reading comprehension strategies for English learners": {"pclass": "English", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "No", "Context": "No"},
    "Write a research summary on the social impact of digital media": {"pclass": "Social Studies", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "You're a physics teacher. Explain Newton’s laws of motion with examples": {"pclass": "Science", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "Yes", "Context": "Yes"},
    "Give advice on balancing school and extracurricular activities": {"pclass": "Social Studies", "sclass": "Self Help/Advice", "Profane": "No", "Writing": "No", "Context": "No"},
    "Write an essay on the evolution of artificial intelligence": {"pclass": "Technology", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "You're a math professor. Teach the concept of derivatives": {"pclass": "Mathematics", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "Yes", "Context": "Yes"},
    "Explain the benefits of sustainable architecture in engineering": {"pclass": "Engineering", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "Provide guidance on effective essay writing for English literature": {"pclass": "English", "sclass": "Teaching/Guidance", "Profane": "No", "Writing": "No", "Context": "No"},
    "Write a research summary on the effects of climate change on agriculture": {"pclass": "Science", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "No"},
    "You're a history mentor. Summarize the causes and effects of the French Revolution": {"pclass": "Social Studies", "sclass": "Research/Informative", "Profane": "No", "Writing": "Yes", "Context": "Yes"},
    "Give advice on improving problem-solving skills in physics": {"pclass": "Science", "sclass": "Self Help/Advice", "Profane": "No", "Writing": "No", "Context": "No"},

}
