data = {
    # Computer Science / Research
    "What is Python?": {"pclass": "Computer Science", "sclass": "Research/Informative"},
    "How does a binary search algorithm work?": {"pclass": "Computer Science", "sclass": "Research/Informative"},
    "What is the difference between Java and JavaScript?": {"pclass": "Computer Science", "sclass": "Research/Informative"},
    "Explain object-oriented programming concepts.": {"pclass": "Computer Science", "sclass": "Research/Informative"},
    "What are the key features of Linux?": {"pclass": "Computer Science", "sclass": "Research/Informative"},
    "How does a neural network learn?": {"pclass": "Computer Science", "sclass": "Research/Informative"},
    "What is the function of an operating system?": {"pclass": "Computer Science", "sclass": "Research/Informative"},
    "How do databases store information?": {"pclass": "Computer Science", "sclass": "Research/Informative"},
    "Explain recursion with an example.": {"pclass": "Computer Science", "sclass": "Research/Informative"},
    "What is a hash table and how does it work?": {"pclass": "Computer Science", "sclass": "Research/Informative"},
    "Describe the differences between TCP and UDP.": {"pclass": "Computer Science", "sclass": "Research/Informative"},
    "What are some common programming paradigms?": {"pclass": "Computer Science", "sclass": "Research/Informative"},
    "How do compilers convert code into machine language?": {"pclass": "Computer Science", "sclass": "Research/Informative"},
    "What is the purpose of version control systems?": {"pclass": "Computer Science", "sclass": "Research/Informative"},
    "Explain cloud computing in simple terms.": {"pclass": "Computer Science", "sclass": "Research/Informative"},

    # History / Research
    "Who was Ghengis Khan?": {"pclass": "History", "sclass": "Research/Informative"},
    "What caused the fall of the Roman Empire?": {"pclass": "History", "sclass": "Research/Informative"},
    "Explain the significance of the French Revolution.": {"pclass": "History", "sclass": "Research/Informative"},
    "Who was Cleopatra?": {"pclass": "History", "sclass": "Research/Informative"},
    "What were the main causes of World War I?": {"pclass": "History", "sclass": "Research/Informative"},
    "Describe the Renaissance period in Europe.": {"pclass": "History", "sclass": "Research/Informative"},
    "What led to the American Civil War?": {"pclass": "History", "sclass": "Research/Informative"},
    "Who was Napoleon Bonaparte?": {"pclass": "History", "sclass": "Research/Informative"},
    "Explain the Cold War in simple terms.": {"pclass": "History", "sclass": "Research/Informative"},
    "What was the Industrial Revolution?": {"pclass": "History", "sclass": "Research/Informative"},
    "Who signed the Magna Carta?": {"pclass": "History", "sclass": "Research/Informative"},
    "Describe the causes of the French and Indian War.": {"pclass": "History", "sclass": "Research/Informative"},
    "What was the significance of the Berlin Wall?": {"pclass": "History", "sclass": "Research/Informative"},
    "Who were the Vikings and where did they travel?": {"pclass": "History", "sclass": "Research/Informative"},
    "What is the history of the Silk Road?": {"pclass": "History", "sclass": "Research/Informative"},

    # Self Help / Advice
    "How can I study more effectively?": {"pclass": "Self Help", "sclass": "Advice/Guidance"},
    "What time should I go to bed?": {"pclass": "Self Help", "sclass": "Advice/Guidance"},
    "How do I improve my focus while working?": {"pclass": "Self Help", "sclass": "Advice/Guidance"},
    "How can I manage my stress better?": {"pclass": "Self Help", "sclass": "Advice/Guidance"},
    "What are good habits for productivity?": {"pclass": "Self Help", "sclass": "Advice/Guidance"},
    "How can I improve my memory?": {"pclass": "Self Help", "sclass": "Advice/Guidance"},
    "What are effective time management strategies?": {"pclass": "Self Help", "sclass": "Advice/Guidance"},
    "How do I stay motivated to exercise?": {"pclass": "Self Help", "sclass": "Advice/Guidance"},
    "What are tips for better concentration?": {"pclass": "Self Help", "sclass": "Advice/Guidance"},
    "How can I build confidence?": {"pclass": "Self Help", "sclass": "Advice/Guidance"},
    "How can I improve my public speaking skills?": {"pclass": "Self Help", "sclass": "Advice/Guidance"},
    "What are ways to maintain a positive mindset?": {"pclass": "Self Help", "sclass": "Advice/Guidance"},
    "How do I avoid procrastination?": {"pclass": "Self Help", "sclass": "Advice/Guidance"},
    "What are effective study techniques for exams?": {"pclass": "Self Help", "sclass": "Advice/Guidance"},
    "How can I better handle criticism?": {"pclass": "Self Help", "sclass": "Advice/Guidance"},

    # Mathematics / Teaching
    "Whats the factored form of 2x^2 + 3x - 5": {"pclass": "Mathematics", "sclass": "Teaching"},
    "How can I solve for x in 7x + 8 = 5": {"pclass": "Mathematics", "sclass": "Teaching"},
    "What is the derivative of x^2 + 3x?": {"pclass": "Mathematics", "sclass": "Teaching"},
    "How do you calculate the area of a circle?": {"pclass": "Mathematics", "sclass": "Teaching"},
    "Explain the Pythagorean theorem with an example.": {"pclass": "Mathematics", "sclass": "Teaching"},
    "How do you solve a quadratic equation?": {"pclass": "Mathematics", "sclass": "Teaching"},
    "What is an integral and how is it calculated?": {"pclass": "Mathematics", "sclass": "Teaching"},
    "Explain how to find the slope of a line.": {"pclass": "Mathematics", "sclass": "Teaching"},
    "What is the difference between permutation and combination?": {"pclass": "Mathematics", "sclass": "Teaching"},
    "How do you calculate the volume of a cylinder?": {"pclass": "Mathematics", "sclass": "Teaching"},
    "Explain the concept of limits in calculus.": {"pclass": "Mathematics", "sclass": "Teaching"},
    "How do you convert fractions to decimals?": {"pclass": "Mathematics", "sclass": "Teaching"},
    "What are prime numbers and how to identify them?": {"pclass": "Mathematics", "sclass": "Teaching"},
    "Explain the difference between mean, median, and mode.": {"pclass": "Mathematics", "sclass": "Teaching"},
    "How do you solve systems of linear equations?": {"pclass": "Mathematics", "sclass": "Teaching"}
}
